#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path("../lib", __FILE__)
require "dsl/python/cli"

if ARGV.size.zero?
  Dsl::Python.open_repl
elsif ["v", "-v", "--version", "-V"].include? ARGV.first
  Dsl::Python.show_version
elsif ["h", "-h", "--help", "-?"].include? ARGV.first
  Dsl::Python.show_help
else
  run_program ARGV.first
end
