#!/usr/bin/env ruby
require_relative "lib/dsl/python/cli"

if ARGV.size.zero?
  open_repl
elsif ["-v", "--version", "-V"].include? ARGV.first
  show_version
elsif ["-h", "--help", "-?"].include? ARGV.first
  show_help
else
  run_program ARGV.first
end
